# -*- coding: utf-8 -*-
"""DLFA4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuBY-nIYJVBq3U19A7O3M92wN4lSYpaV
"""

pip install torch --upgrade

pip install transformers --upgrade

pip install torch==2.0.0 transformers==4.30.0

# installation of required packages - portallocker, torchtext, torchinfo,---
!pip -q install portalocker
!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install -q torchtext==0.15.2
!pip install -q torchinfo

!pip install datasets

"""# Task 1

Loading the dataset and preprocessing according to the provided guidelines in the assignment.
"""

from datasets import load_dataset

SST2 = load_dataset("sst2")
SST21 = load_dataset("SetFit/sst2")
train_iter = SST2['train']
val_iter = SST2['validation']
test_iter = SST21['test']

# Convert dataset objects to lists
train_data = list(train_iter)
val_data = list(val_iter)
test_data = list(test_iter)

# Show a few samples
print("Example from train_data:")
print(train_data[0])

SST21

# Displaying some samples and corresponding labels
train_data[0:5]

import torchtext
import string
from torchtext.vocab import build_vocab_from_iterator
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from torchinfo import summary
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt

import nltk
import re
from transformers import BertTokenizer

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Preprocess: lowercase, remove punctuation and stopwords
def preprocess_text(text):
    text = text.lower()
    text = re.sub(f"[{string.punctuation}]", "", text)
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    return tokens

# Apply preprocessing to all splits
train_tokens = [(preprocess_text(data['sentence']), data['label']) for data in train_data]
val_tokens = [(preprocess_text(data['sentence']), data['label']) for data in val_data]
test_tokens = [(preprocess_text(data['text']), data['label']) for data in test_data]

def yield_tokens(data_iters):
    for data_iter in data_iters:
        for tokens, _ in data_iter:
            yield tokens

# Building vocabulary
vocab = build_vocab_from_iterator(yield_tokens([train_tokens, val_tokens]), specials=["<pad>", "<unk>"])
vocab.set_default_index(vocab["<unk>"])
print("Vocabulary size:", len(vocab))

# conversion from tokens to indices using torchtext vocab
sample_tokens = train_tokens[0][0]  # To get tokens from first sample
print("Sample preprocessed tokens:", sample_tokens)

numericalized = vocab(sample_tokens)
print("Numericalized token indices (torchtext.vocab):", numericalized)

bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# preprocessed tokens back into strings
def reconstruct_text(tokenized_data):
    return [" ".join(tokens) for tokens, _ in tokenized_data]

# Tokenize with BERT
def bert_tokenize_and_convert(tokenized_data):
    cleaned_texts = reconstruct_text(tokenized_data)
    encodings = bert_tokenizer(
        cleaned_texts,
        padding=True,
        truncation=True,
        max_length=64,
        return_tensors='pt'
    )
    return encodings

train_encodings = bert_tokenize_and_convert(train_tokens)
val_encodings = bert_tokenize_and_convert(val_tokens)
test_encodings = bert_tokenize_and_convert(test_tokens)

# one hot encoding
def one_hot_encode(labels, num_classes=2):
    return torch.eye(num_classes)[torch.tensor(labels)]

train_labels = one_hot_encode([label for _, label in train_tokens])
val_labels = one_hot_encode([label for _, label in val_tokens])
test_labels = one_hot_encode([label for _, label in test_tokens])

# Checking shapes of each data split
print("Train input_ids shape:", train_encodings['input_ids'].shape)
print("Train labels shape:", train_labels.shape)
print("Val input_ids shape:", val_encodings['input_ids'].shape)
print("Val labels shape:", val_labels.shape)
print("Test input_ids shape:", test_encodings['input_ids'].shape)
print("Test labels shape:", test_labels.shape)

"""# Task 2

The taken dataset is already having test, validation and train splits, thats why i am not splitting again like merging train and validation  and again splitting. Although sst2 dataset test dataset dont have labels(-1), i took test data set from hugging face where test split also have labels.
"""

from collections import Counter
import matplotlib.pyplot as plt

# counting labels (number and labels and number of classes)
labels_list = [data_point['label'] for data_point in train_data]
label_counts = Counter(labels_list)

# Plot
labels = ["negative", "positive"]
counts = [label_counts[0], label_counts[1]]

plt.bar(labels, counts, color=["crimson", "mediumseagreen"])
plt.title("Label Distribution in Training Set")
plt.xlabel("Sentiment Class")
plt.ylabel("Count")
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.show()

# Print counts
print("Label counts in training data:")
for idx, count in label_counts.items():
    sentiment = "negative" if idx == 0 else "positive"
    print(f"{sentiment}: {count}")

# Get all unique labels from the train set
unique_labels = set([sample['label'] for sample in train_data])
print("Unique labels in train_data:", unique_labels)

#  Get all unique labels from the validation set
unique_val_labels = set([sample['label'] for sample in val_data])
print("Unique labels in val_data:", unique_val_labels)

# Get all unique labels from the test set
unique_test_labels = set([sample['label'] for sample in test_data])
print("Unique labels in test_data:", unique_test_labels)

# displaying samples in each dataset and with respect to the class
from collections import Counter

train_label_counts = Counter([sample['label'] for sample in train_data])
print("Train label counts:", train_label_counts)

val_label_counts = Counter([sample['label'] for sample in val_data])
print("Validation label counts:", val_label_counts)

test_label_counts = Counter([sample['label'] for sample in test_data])
print("Test label counts:", test_label_counts)

"""# task 3"""

import torch
import torch.nn as nn

class DefinedTransformerEncoderLayer(nn.Module):
    def __init__(self, d_model=16, nhead=4, dropout=0.5):
        super().__init__()

        # Multi-head Self Attention
        self.self_attn = nn.MultiheadAttention(embed_dim=d_model, num_heads=nhead, dropout=dropout, batch_first=True)

        # Feedforward Neural Network (1 hidden layer, as per assignment)
        self.linear1 = nn.Linear(d_model, d_model)
        self.linear2 = nn.Linear(d_model, d_model)

        # Dropout
        self.dropout = nn.Dropout(dropout)

        # Layer Normalization
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)

    def forward(self, x):
        # Self-attention + residual + norm
        attn_output, _ = self.self_attn(x, x, x)
        x = self.norm1(x + self.dropout(attn_output))

        # Feedforward + residual + norm
        ff_output = self.linear2(torch.relu(self.linear1(x)))
        x = self.norm2(x + self.dropout(ff_output))

        return x

import math
import torch.nn as nn

class PositionalEncoding(nn.Module):
    def __init__(self, d_model=16, max_len=5000):
        super().__init__()
        pe = torch.zeros(max_len, d_model)  # Shape: (max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)  # Shape: (1, max_len, d_model)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)]

class TransformerClassifier(nn.Module):
    def __init__(self, vocab_size, d_model=16, nhead=4, num_layers=1, num_classes=2, dropout=0.5, max_len=5000):
        super().__init__()

        # 1. Embedding layer
        self.embedding = nn.Embedding(vocab_size, d_model)

        # 2. Positional encoding
        self.pos_encoder = PositionalEncoding(d_model, max_len)

        # 3. Dropout after position encoding
        self.dropout = nn.Dropout(dropout)

        # 4. Stack of encoder layers
        self.encoder_layers = nn.ModuleList([DefinedTransformerEncoderLayer(d_model, nhead, dropout)for _ in range(num_layers)])

        # 5. Classification head
        self.classifier = nn.Linear(d_model, num_classes)

    def forward(self, x):
        x = self.embedding(x)              # Shape: (batch, seq_len, d_model)
        x = self.pos_encoder(x)            # Add positional info
        x = self.dropout(x)

        for layer in self.encoder_layers:
            x = layer(x)                   # Pass through custom transformer blocks

        x = x.mean(dim=1)                  # Global average pooling over sequence
        return self.classifier(x)

from torch.utils.data import TensorDataset, DataLoader

# Convert one-hot labels to class indices
train_targets = train_labels.argmax(dim=1)
val_targets = val_labels.argmax(dim=1)

# Create TensorDatasets
train_dataset = TensorDataset(train_encodings['input_ids'], train_targets)
val_dataset = TensorDataset(val_encodings['input_ids'], val_targets)

# Create DataLoaders
BATCH_SIZE = 32

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)

VOCAB_SIZE = 30522 # BERT tokenizer's vocab size
model = TransformerClassifier(vocab_size=VOCAB_SIZE).to("cuda" if torch.cuda.is_available() else "cpu")

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

# Use device consistently
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model

# defining training model

def train_model(model, train_loader, val_loader, criterion, optimizer, epochs=5):
    train_losses, val_losses = [], []
    train_accuracies, val_accuracies = [], []

    model.to(device)

    for epoch in range(epochs):
        model.train()
        total_loss = 0
        correct_preds, total_samples = 0, 0

        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)
            correct_preds += (preds == labels).sum().item()
            total_samples += labels.size(0)

        avg_train_loss = total_loss / len(train_loader)
        train_accuracy = correct_preds / total_samples
        train_losses.append(avg_train_loss)
        train_accuracies.append(train_accuracy)

        # Validation Phase
        model.eval()
        val_loss = 0
        correct_val_preds, total_val_samples = 0, 0

        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)

                outputs = model(inputs)
                loss = criterion(outputs, labels)
                val_loss += loss.item()

                preds = torch.argmax(outputs, dim=1)
                correct_val_preds += (preds == labels).sum().item()
                total_val_samples += labels.size(0)

        avg_val_loss = val_loss / len(val_loader)
        val_accuracy = correct_val_preds / total_val_samples
        val_losses.append(avg_val_loss)
        val_accuracies.append(val_accuracy)

        print(f"Epoch {epoch+1}/{epochs} | "
              f"Train Loss: {avg_train_loss:.4f}, Train Acc: {train_accuracy:.4f} | "
              f"Val Loss: {avg_val_loss:.4f}, Val Acc: {val_accuracy:.4f}")

    # Plotting Loss and Accuracy during training
    epochs_range = range(1, epochs+1)

    plt.figure(figsize=(12, 5))

    # Loss Plots
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, train_losses, label="Train Loss", marker='o')
    plt.plot(epochs_range, val_losses, label="Val Loss", marker='s')
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training vs Validation Loss")
    plt.legend()
    plt.grid(True)

    # Accuracy Plots
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, train_accuracies, label="Train Accuracy", marker='o')
    plt.plot(epochs_range, val_accuracies, label="Val Accuracy", marker='s')
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.title("Training vs Validation Accuracy")
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

    return train_losses, val_losses, train_accuracies, val_accuracies

train_losses, val_losses, train_accuracies, val_accuracies = train_model(model, train_loader, val_loader, criterion, optimizer, epochs=5)

from torch.utils.data import TensorDataset, DataLoader

# Convert one-hot to class indices
test_targets = test_labels.argmax(dim=1)

# TensorDataset and DataLoader
test_dataset = TensorDataset(test_encodings['input_ids'], test_targets)
test_loader = DataLoader(test_dataset, batch_size=32)

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix


def evaluate_model(model, test_loader):
    model.eval()
    model.to(device)

    all_preds = []
    all_labels = []

    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            outputs = model(inputs)
            preds = torch.argmax(outputs, dim=1)

            all_preds.extend(preds.cpu().tolist())
            all_labels.extend(labels.cpu().tolist())

    acc = accuracy_score(all_labels, all_preds)
    precision = precision_score(all_labels, all_preds)
    recall = recall_score(all_labels, all_preds)
    cm = confusion_matrix(all_labels, all_preds)

    print(f"\nTest Accuracy:  {acc:.4f}")
    print(f"Test Precision: {precision:.4f}")
    print(f"Test Recall:    {recall:.4f}")

    # Heatmap
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=["Negative", "Positive"],
                yticklabels=["Negative", "Positive"])
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")
    plt.show()

    #return acc, precision, recall, cm

evaluate_model(model, test_loader)

"""# Task 4"""

class TransformerClassifier_lib(nn.Module):
    def __init__(self, vocab_size, d_model=16, nhead=4, num_layers=1, num_classes=2, dropout=0.5, max_len=5000):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoder = PositionalEncoding(d_model, max_len)
        self.dropout = nn.Dropout(dropout)

        # Built-in TransformerEncoderLayer and TransformerEncoder
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, dropout=dropout, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        self.classifier = nn.Linear(d_model, num_classes)

    def forward(self, x):
        x = self.embedding(x)
        x = self.pos_encoder(x)
        x = self.dropout(x)

        x = self.transformer_encoder(x)
        x = x.mean(dim=1)  # Global average pooling
        return self.classifier(x)

model_builtin = TransformerClassifier_lib(vocab_size=30522).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_builtin.parameters(), lr=1e-3)

model_builtin

train_losses, val_losses, train_accuracies, val_accuracies = train_model(model_builtin, train_loader, val_loader, criterion, optimizer, epochs=5)

evaluate_model(model_builtin, test_loader)

"""# Task 5"""

from transformers import BertModel

class BERTClassifier(nn.Module):
    def __init__(self, dropout=0.5, num_classes=2):
        super().__init__()
        self.bert = BertModel.from_pretrained("bert-base-uncased")
        for param in self.bert.parameters():
            param.requires_grad = False

        self.dropout = nn.Dropout(dropout)
        self.classifier = nn.Linear(self.bert.config.hidden_size, num_classes)

    def forward(self, input_ids, attention_mask=None):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.pooler_output  # (batch_size, hidden_size)
        x = self.dropout(pooled_output)
        return self.classifier(x)

def train_bert_model(model, train_loader, val_loader, criterion, optimizer, epochs=5):
    train_losses, val_losses = [], []
    train_accuracies, val_accuracies = [], []

    model.to(device)

    for epoch in range(epochs):
        model.train()
        total_loss, correct, total = 0, 0, 0

        for input_ids, attention_mask, labels in train_loader:
            input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(input_ids, attention_mask)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

        train_losses.append(total_loss / len(train_loader))
        train_accuracies.append(correct / total)

        # Validation phase
        model.eval()
        val_loss, correct, total = 0, 0, 0

        with torch.no_grad():
            for input_ids, attention_mask, labels in val_loader:
                input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)
                outputs = model(input_ids, attention_mask)
                loss = criterion(outputs, labels)

                val_loss += loss.item()
                preds = outputs.argmax(dim=1)
                correct += (preds == labels).sum().item()
                total += labels.size(0)

        val_losses.append(val_loss / len(val_loader))
        val_accuracies.append(correct / total)

        print(f"Epoch {epoch+1}/{epochs} | "
              f"Train Loss: {train_losses[-1]:.4f}, Acc: {train_accuracies[-1]:.4f} | "
              f"Val Loss: {val_losses[-1]:.4f}, Acc: {val_accuracies[-1]:.4f}")

    # Plotting loss
    epochs_range = range(1, epochs+1)
    plt.figure(figsize=(12,5))

    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, train_losses, label="Train Loss")
    plt.plot(epochs_range, val_losses, label="Val Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Loss Curve")
    plt.legend()

    # Plotting accuracy
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, train_accuracies, label="Train Acc")
    plt.plot(epochs_range, val_accuracies, label="Val Acc")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.title("Accuracy Curve")
    plt.legend()

    plt.tight_layout()
    plt.show()

model_bert = BERTClassifier().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_bert.parameters(), lr=1e-3)

# Create datasets (attention_mask is all 1s since no padding tokens)
train_dataset1 = TensorDataset(train_encodings['input_ids'],torch.ones_like(train_encodings['input_ids']),train_labels.argmax(dim=1))

val_dataset1 = TensorDataset(val_encodings['input_ids'],torch.ones_like(val_encodings['input_ids']),val_labels.argmax(dim=1))

test_dataset1 = TensorDataset(test_encodings['input_ids'],torch.ones_like(test_encodings['input_ids']),test_labels.argmax(dim=1))

# DataLoaders
train_loader1 = DataLoader(train_dataset1, batch_size=32, shuffle=True)
val_loader1 = DataLoader(val_dataset1, batch_size=32)
test_loader1 = DataLoader(test_dataset1, batch_size=32)

model_bert

train_bert_model(model_bert, train_loader1, val_loader1, criterion, optimizer, epochs=5)

def evaluate_bert_model(model, test_loader):
    model.eval()
    model.to(device)

    all_preds, all_labels = [], []

    with torch.no_grad():
        for input_ids, attention_mask, labels in test_loader:
            input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)
            outputs = model(input_ids, attention_mask)
            preds = outputs.argmax(dim=1)

            all_preds.extend(preds.cpu().tolist())
            all_labels.extend(labels.cpu().tolist())

    acc = accuracy_score(all_labels, all_preds)
    prec = precision_score(all_labels, all_preds)

    print(f"\n Test Accuracy:  {acc:.4f}")
    print(f"Test Precision: {prec:.4f}")

    sns.heatmap(confusion_matrix(all_labels, all_preds), annot=True, fmt='d',
                xticklabels=["Negative", "Positive"], yticklabels=["Negative", "Positive"],
                cmap="Blues")
    plt.title("Confusion Matrix - BERT Classifier")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

evaluate_bert_model(model_bert, test_loader1)

"""# Task 6"""

from torchinfo import summary

summary(model,input_data=torch.randint(0, len(vocab), (32, 64), dtype=torch.long).to(device), col_names=["input_size", "output_size", "num_params"])

summary(model_builtin, input_data=torch.randint(0, 30522, (32, 64), dtype=torch.long).to(device), col_names=["input_size", "output_size", "num_params"])

summary(model_bert, input_data=(torch.randint(0, 30522, (32, 64)).to(device), torch.ones(32, 64).to(device)),col_names=["input_size", "output_size", "num_params"])

